version: "3.9"
services:
  authorizer:
    build: .
    ports:
      - 19898:8080
    volumes:
      - ./configs/llm:/authorizer/configs/llm:ro
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 19897:5432
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --requirepass QpdUm3KNMXwya8Mjiuxiang
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - ../redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
