# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_stream_pb2 as ai__service__stream__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIStreamServiceStub(object):
    """AI服务接口 - 流式版本
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/ai_service.AIStreamService/StreamChat',
                request_serializer=ai__service__stream__pb2.StreamChatRequest.SerializeToString,
                response_deserializer=ai__service__stream__pb2.StreamChatResponse.FromString,
                _registered_method=True)
        self.StreamWorkflowExecute = channel.unary_stream(
                '/ai_service.AIStreamService/StreamWorkflowExecute',
                request_serializer=ai__service__stream__pb2.StreamWorkflowRequest.SerializeToString,
                response_deserializer=ai__service__stream__pb2.StreamWorkflowResponse.FromString,
                _registered_method=True)
        self.StreamWorkflowGenerate = channel.unary_stream(
                '/ai_service.AIStreamService/StreamWorkflowGenerate',
                request_serializer=ai__service__stream__pb2.StreamWorkflowRequest.SerializeToString,
                response_deserializer=ai__service__stream__pb2.StreamWorkflowResponse.FromString,
                _registered_method=True)


class AIStreamServiceServicer(object):
    """AI服务接口 - 流式版本
    """

    def StreamChat(self, request, context):
        """流式聊天接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWorkflowExecute(self, request, context):
        """流式工作流执行
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWorkflowGenerate(self, request, context):
        """流式工作流生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=ai__service__stream__pb2.StreamChatRequest.FromString,
                    response_serializer=ai__service__stream__pb2.StreamChatResponse.SerializeToString,
            ),
            'StreamWorkflowExecute': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWorkflowExecute,
                    request_deserializer=ai__service__stream__pb2.StreamWorkflowRequest.FromString,
                    response_serializer=ai__service__stream__pb2.StreamWorkflowResponse.SerializeToString,
            ),
            'StreamWorkflowGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWorkflowGenerate,
                    request_deserializer=ai__service__stream__pb2.StreamWorkflowRequest.FromString,
                    response_serializer=ai__service__stream__pb2.StreamWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AIStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIStreamService(object):
    """AI服务接口 - 流式版本
    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.AIStreamService/StreamChat',
            ai__service__stream__pb2.StreamChatRequest.SerializeToString,
            ai__service__stream__pb2.StreamChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWorkflowExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.AIStreamService/StreamWorkflowExecute',
            ai__service__stream__pb2.StreamWorkflowRequest.SerializeToString,
            ai__service__stream__pb2.StreamWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWorkflowGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_service.AIStreamService/StreamWorkflowGenerate',
            ai__service__stream__pb2.StreamWorkflowRequest.SerializeToString,
            ai__service__stream__pb2.StreamWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
