// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: ai_service_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIStreamService_StreamChat_FullMethodName             = "/ai_service.AIStreamService/StreamChat"
	AIStreamService_StreamWorkflowExecute_FullMethodName  = "/ai_service.AIStreamService/StreamWorkflowExecute"
	AIStreamService_StreamWorkflowGenerate_FullMethodName = "/ai_service.AIStreamService/StreamWorkflowGenerate"
)

// AIStreamServiceClient is the client API for AIStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI服务接口 - 流式版本
type AIStreamServiceClient interface {
	// 流式聊天接口
	StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResponse], error)
	// 流式工作流执行
	StreamWorkflowExecute(ctx context.Context, in *StreamWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkflowResponse], error)
	// 流式工作流生成
	StreamWorkflowGenerate(ctx context.Context, in *StreamWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkflowResponse], error)
}

type aIStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIStreamServiceClient(cc grpc.ClientConnInterface) AIStreamServiceClient {
	return &aIStreamServiceClient{cc}
}

func (c *aIStreamServiceClient) StreamChat(ctx context.Context, in *StreamChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIStreamService_ServiceDesc.Streams[0], AIStreamService_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChatRequest, StreamChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamChatClient = grpc.ServerStreamingClient[StreamChatResponse]

func (c *aIStreamServiceClient) StreamWorkflowExecute(ctx context.Context, in *StreamWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkflowResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIStreamService_ServiceDesc.Streams[1], AIStreamService_StreamWorkflowExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkflowRequest, StreamWorkflowResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamWorkflowExecuteClient = grpc.ServerStreamingClient[StreamWorkflowResponse]

func (c *aIStreamServiceClient) StreamWorkflowGenerate(ctx context.Context, in *StreamWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamWorkflowResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIStreamService_ServiceDesc.Streams[2], AIStreamService_StreamWorkflowGenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkflowRequest, StreamWorkflowResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamWorkflowGenerateClient = grpc.ServerStreamingClient[StreamWorkflowResponse]

// AIStreamServiceServer is the server API for AIStreamService service.
// All implementations must embed UnimplementedAIStreamServiceServer
// for forward compatibility.
//
// AI服务接口 - 流式版本
type AIStreamServiceServer interface {
	// 流式聊天接口
	StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatResponse]) error
	// 流式工作流执行
	StreamWorkflowExecute(*StreamWorkflowRequest, grpc.ServerStreamingServer[StreamWorkflowResponse]) error
	// 流式工作流生成
	StreamWorkflowGenerate(*StreamWorkflowRequest, grpc.ServerStreamingServer[StreamWorkflowResponse]) error
	mustEmbedUnimplementedAIStreamServiceServer()
}

// UnimplementedAIStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIStreamServiceServer struct{}

func (UnimplementedAIStreamServiceServer) StreamChat(*StreamChatRequest, grpc.ServerStreamingServer[StreamChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedAIStreamServiceServer) StreamWorkflowExecute(*StreamWorkflowRequest, grpc.ServerStreamingServer[StreamWorkflowResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWorkflowExecute not implemented")
}
func (UnimplementedAIStreamServiceServer) StreamWorkflowGenerate(*StreamWorkflowRequest, grpc.ServerStreamingServer[StreamWorkflowResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWorkflowGenerate not implemented")
}
func (UnimplementedAIStreamServiceServer) mustEmbedUnimplementedAIStreamServiceServer() {}
func (UnimplementedAIStreamServiceServer) testEmbeddedByValue()                         {}

// UnsafeAIStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIStreamServiceServer will
// result in compilation errors.
type UnsafeAIStreamServiceServer interface {
	mustEmbedUnimplementedAIStreamServiceServer()
}

func RegisterAIStreamServiceServer(s grpc.ServiceRegistrar, srv AIStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIStreamService_ServiceDesc, srv)
}

func _AIStreamService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIStreamServiceServer).StreamChat(m, &grpc.GenericServerStream[StreamChatRequest, StreamChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamChatServer = grpc.ServerStreamingServer[StreamChatResponse]

func _AIStreamService_StreamWorkflowExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIStreamServiceServer).StreamWorkflowExecute(m, &grpc.GenericServerStream[StreamWorkflowRequest, StreamWorkflowResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamWorkflowExecuteServer = grpc.ServerStreamingServer[StreamWorkflowResponse]

func _AIStreamService_StreamWorkflowGenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIStreamServiceServer).StreamWorkflowGenerate(m, &grpc.GenericServerStream[StreamWorkflowRequest, StreamWorkflowResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIStreamService_StreamWorkflowGenerateServer = grpc.ServerStreamingServer[StreamWorkflowResponse]

// AIStreamService_ServiceDesc is the grpc.ServiceDesc for AIStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_service.AIStreamService",
	HandlerType: (*AIStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _AIStreamService_StreamChat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWorkflowExecute",
			Handler:       _AIStreamService_StreamWorkflowExecute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWorkflowGenerate",
			Handler:       _AIStreamService_StreamWorkflowGenerate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai_service_stream.proto",
}
