// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ai_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建智能体任务
type CreateAgentTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentType       string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`                                                            // 智能体类型
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                     // 用户ID
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                                            // 会话ID
	TaskDescription string                 `protobuf:"bytes,4,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`                                          // 任务描述
	Context         map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // 上下文信息
	Parameters      map[string]string      `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 参数
	Priority        int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`                                                                              // 优先级 1-10
	Timeout         int32                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                                                                                // 超时时间(秒)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAgentTaskRequest) Reset() {
	*x = CreateAgentTaskRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentTaskRequest) ProtoMessage() {}

func (x *CreateAgentTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentTaskRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *CreateAgentTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAgentTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateAgentTaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *CreateAgentTaskRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateAgentTaskRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateAgentTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateAgentTaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CreateAgentTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // 任务状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentTaskResponse) Reset() {
	*x = CreateAgentTaskResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentTaskResponse) ProtoMessage() {}

func (x *CreateAgentTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateAgentTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取任务状态
type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID（权限验证）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                                             // 任务ID
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`                                                    // 智能体类型
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                                           // 任务状态
	Result        map[string]string      `protobuf:"bytes,4,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 任务结果
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                                             // 错误信息
	ExecutionTime float64                `protobuf:"fixed64,6,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`                                      // 执行时间(秒)
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                    // 创建时间
	CompletedAt   string                 `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`                                              // 完成时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *GetTaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskStatusResponse) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTaskStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTaskStatusResponse) GetExecutionTime() float64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

func (x *GetTaskStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetTaskStatusResponse) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// 取消任务
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取智能体统计信息
type GetAgentStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatsRequest) Reset() {
	*x = GetAgentStatsRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsRequest) ProtoMessage() {}

func (x *GetAgentStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{6}
}

type GetAgentStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EngineStatus       string                 `protobuf:"bytes,1,opt,name=engine_status,json=engineStatus,proto3" json:"engine_status,omitempty"`                      // 引擎状态
	ActiveTasks        int32                  `protobuf:"varint,2,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`                        // 活跃任务数
	CompletedTasks     int32                  `protobuf:"varint,3,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`               // 已完成任务数
	ActiveAgents       int32                  `protobuf:"varint,4,opt,name=active_agents,json=activeAgents,proto3" json:"active_agents,omitempty"`                     // 活跃智能体数
	QueueSize          int32                  `protobuf:"varint,5,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`                              // 队列大小
	WorkerCount        int32                  `protobuf:"varint,6,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`                        // 工作器数量
	MaxConcurrentTasks int32                  `protobuf:"varint,7,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"` // 最大并发任务数
	AgentTypes         []string               `protobuf:"bytes,8,rep,name=agent_types,json=agentTypes,proto3" json:"agent_types,omitempty"`                            // 支持的智能体类型
	Uptime             string                 `protobuf:"bytes,9,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                      // 运行时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAgentStatsResponse) Reset() {
	*x = GetAgentStatsResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatsResponse) ProtoMessage() {}

func (x *GetAgentStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentStatsResponse) GetEngineStatus() string {
	if x != nil {
		return x.EngineStatus
	}
	return ""
}

func (x *GetAgentStatsResponse) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *GetAgentStatsResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *GetAgentStatsResponse) GetActiveAgents() int32 {
	if x != nil {
		return x.ActiveAgents
	}
	return 0
}

func (x *GetAgentStatsResponse) GetQueueSize() int32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *GetAgentStatsResponse) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *GetAgentStatsResponse) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *GetAgentStatsResponse) GetAgentTypes() []string {
	if x != nil {
		return x.AgentTypes
	}
	return nil
}

func (x *GetAgentStatsResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

// 列出用户任务
type ListUserTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                // 限制数量
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`              // 偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTasksRequest) Reset() {
	*x = ListUserTasksRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTasksRequest) ProtoMessage() {}

func (x *ListUserTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTasksRequest.ProtoReflect.Descriptor instead.
func (*ListUserTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserTasksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`          // 任务ID
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // 智能体类型
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                        // 状态
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // 开始时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTask) Reset() {
	*x = UserTask{}
	mi := &file_proto_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTask) ProtoMessage() {}

func (x *UserTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTask.ProtoReflect.Descriptor instead.
func (*UserTask) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *UserTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UserTask) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *UserTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserTask) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type ListUserTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*UserTask            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`  // 任务列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTasksResponse) Reset() {
	*x = ListUserTasksResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTasksResponse) ProtoMessage() {}

func (x *ListUserTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTasksResponse.ProtoReflect.Descriptor instead.
func (*ListUserTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserTasksResponse) GetTasks() []*UserTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListUserTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 模型推理接口
type InferModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                                            // 模型名称
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                     // 用户ID
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`                                                                               // 消息列表
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferModelRequest) Reset() {
	*x = InferModelRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferModelRequest) ProtoMessage() {}

func (x *InferModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferModelRequest.ProtoReflect.Descriptor instead.
func (*InferModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *InferModelRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *InferModelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InferModelRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InferModelRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // 角色：user/assistant/system
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InferModelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Response       string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`                                    // 响应内容
	ModelUsed      string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`                 // 使用的模型
	TokensUsed     int32                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`             // 使用的token数
	PointsConsumed int32                  `protobuf:"varint,4,opt,name=points_consumed,json=pointsConsumed,proto3" json:"points_consumed,omitempty"` // 消耗的积分
	FinishReason   string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`        // 完成原因
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferModelResponse) Reset() {
	*x = InferModelResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferModelResponse) ProtoMessage() {}

func (x *InferModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferModelResponse.ProtoReflect.Descriptor instead.
func (*InferModelResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *InferModelResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *InferModelResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *InferModelResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *InferModelResponse) GetPointsConsumed() int32 {
	if x != nil {
		return x.PointsConsumed
	}
	return 0
}

func (x *InferModelResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// 工作流执行接口
type ExecuteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`                                           // 工作流名称
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                             // 用户ID
	Inputs        map[string]string      `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 输入参数
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`                                                   // 工作流执行ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                             // 状态
	Outputs       map[string]string      `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 输出结果
	Steps         []*WorkflowStep        `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`                                                                               // 执行步骤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecuteWorkflowResponse) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type WorkflowStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`                                                         // 步骤名称
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                             // 状态
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                      // 开始时间
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                            // 结束时间
	Outputs       map[string]string      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 步骤输出
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                                                               // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_proto_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *WorkflowStep) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *WorkflowStep) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStep) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *WorkflowStep) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *WorkflowStep) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *WorkflowStep) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\n" +
	"ai_service\"\xea\x03\n" +
	"\x16CreateAgentTaskRequest\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12)\n" +
	"\x10task_description\x18\x04 \x01(\tR\x0ftaskDescription\x12I\n" +
	"\acontext\x18\x05 \x03(\v2/.ai_service.CreateAgentTaskRequest.ContextEntryR\acontext\x12R\n" +
	"\n" +
	"parameters\x18\x06 \x03(\v22.ai_service.CreateAgentTaskRequest.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x18\n" +
	"\atimeout\x18\b \x01(\x05R\atimeout\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x17CreateAgentTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"H\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xe8\x02\n" +
	"\x15GetTaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12E\n" +
	"\x06result\x18\x04 \x03(\v2-.ai_service.GetTaskStatusResponse.ResultEntryR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12%\n" +
	"\x0eexecution_time\x18\x06 \x01(\x01R\rexecutionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\tR\vcompletedAt\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetAgentStatsRequest\"\xda\x02\n" +
	"\x15GetAgentStatsResponse\x12#\n" +
	"\rengine_status\x18\x01 \x01(\tR\fengineStatus\x12!\n" +
	"\factive_tasks\x18\x02 \x01(\x05R\vactiveTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x03 \x01(\x05R\x0ecompletedTasks\x12#\n" +
	"\ractive_agents\x18\x04 \x01(\x05R\factiveAgents\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x05 \x01(\x05R\tqueueSize\x12!\n" +
	"\fworker_count\x18\x06 \x01(\x05R\vworkerCount\x120\n" +
	"\x14max_concurrent_tasks\x18\a \x01(\x05R\x12maxConcurrentTasks\x12\x1f\n" +
	"\vagent_types\x18\b \x03(\tR\n" +
	"agentTypes\x12\x16\n" +
	"\x06uptime\x18\t \x01(\tR\x06uptime\"]\n" +
	"\x14ListUserTasksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x98\x01\n" +
	"\bUserTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\"Y\n" +
	"\x15ListUserTasksResponse\x12*\n" +
	"\x05tasks\x18\x01 \x03(\v2\x14.ai_service.UserTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8e\x02\n" +
	"\x11InferModelRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\bmessages\x18\x03 \x03(\v2\x17.ai_service.ChatMessageR\bmessages\x12M\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2-.ai_service.InferModelRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xbe\x01\n" +
	"\x12InferModelResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x05R\n" +
	"tokensUsed\x12'\n" +
	"\x0fpoints_consumed\x18\x04 \x01(\x05R\x0epointsConsumed\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\"\xdc\x02\n" +
	"\x16ExecuteWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12F\n" +
	"\x06inputs\x18\x03 \x03(\v2..ai_service.ExecuteWorkflowRequest.InputsEntryR\x06inputs\x12F\n" +
	"\x06config\x18\x04 \x03(\v2..ai_service.ExecuteWorkflowRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x02\n" +
	"\x17ExecuteWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12J\n" +
	"\aoutputs\x18\x03 \x03(\v20.ai_service.ExecuteWorkflowResponse.OutputsEntryR\aoutputs\x12.\n" +
	"\x05steps\x18\x04 \x03(\v2\x18.ai_service.WorkflowStepR\x05steps\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\fWorkflowStep\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\x12?\n" +
	"\aoutputs\x18\x05 \x03(\v2%.ai_service.WorkflowStep.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdf\x04\n" +
	"\tAIService\x12Z\n" +
	"\x0fCreateAgentTask\x12\".ai_service.CreateAgentTaskRequest\x1a#.ai_service.CreateAgentTaskResponse\x12T\n" +
	"\rGetTaskStatus\x12 .ai_service.GetTaskStatusRequest\x1a!.ai_service.GetTaskStatusResponse\x12K\n" +
	"\n" +
	"CancelTask\x12\x1d.ai_service.CancelTaskRequest\x1a\x1e.ai_service.CancelTaskResponse\x12T\n" +
	"\rGetAgentStats\x12 .ai_service.GetAgentStatsRequest\x1a!.ai_service.GetAgentStatsResponse\x12T\n" +
	"\rListUserTasks\x12 .ai_service.ListUserTasksRequest\x1a!.ai_service.ListUserTasksResponse\x12K\n" +
	"\n" +
	"InferModel\x12\x1d.ai_service.InferModelRequest\x1a\x1e.ai_service.InferModelResponse\x12Z\n" +
	"\x0fExecuteWorkflow\x12\".ai_service.ExecuteWorkflowRequest\x1a#.ai_service.ExecuteWorkflowResponseB2Z0github.com/authorizerdev/authorizer/server/protob\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_ai_service_proto_goTypes = []any{
	(*CreateAgentTaskRequest)(nil),  // 0: ai_service.CreateAgentTaskRequest
	(*CreateAgentTaskResponse)(nil), // 1: ai_service.CreateAgentTaskResponse
	(*GetTaskStatusRequest)(nil),    // 2: ai_service.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil),   // 3: ai_service.GetTaskStatusResponse
	(*CancelTaskRequest)(nil),       // 4: ai_service.CancelTaskRequest
	(*CancelTaskResponse)(nil),      // 5: ai_service.CancelTaskResponse
	(*GetAgentStatsRequest)(nil),    // 6: ai_service.GetAgentStatsRequest
	(*GetAgentStatsResponse)(nil),   // 7: ai_service.GetAgentStatsResponse
	(*ListUserTasksRequest)(nil),    // 8: ai_service.ListUserTasksRequest
	(*UserTask)(nil),                // 9: ai_service.UserTask
	(*ListUserTasksResponse)(nil),   // 10: ai_service.ListUserTasksResponse
	(*InferModelRequest)(nil),       // 11: ai_service.InferModelRequest
	(*ChatMessage)(nil),             // 12: ai_service.ChatMessage
	(*InferModelResponse)(nil),      // 13: ai_service.InferModelResponse
	(*ExecuteWorkflowRequest)(nil),  // 14: ai_service.ExecuteWorkflowRequest
	(*ExecuteWorkflowResponse)(nil), // 15: ai_service.ExecuteWorkflowResponse
	(*WorkflowStep)(nil),            // 16: ai_service.WorkflowStep
	nil,                             // 17: ai_service.CreateAgentTaskRequest.ContextEntry
	nil,                             // 18: ai_service.CreateAgentTaskRequest.ParametersEntry
	nil,                             // 19: ai_service.GetTaskStatusResponse.ResultEntry
	nil,                             // 20: ai_service.InferModelRequest.ParametersEntry
	nil,                             // 21: ai_service.ExecuteWorkflowRequest.InputsEntry
	nil,                             // 22: ai_service.ExecuteWorkflowRequest.ConfigEntry
	nil,                             // 23: ai_service.ExecuteWorkflowResponse.OutputsEntry
	nil,                             // 24: ai_service.WorkflowStep.OutputsEntry
}
var file_proto_ai_service_proto_depIdxs = []int32{
	17, // 0: ai_service.CreateAgentTaskRequest.context:type_name -> ai_service.CreateAgentTaskRequest.ContextEntry
	18, // 1: ai_service.CreateAgentTaskRequest.parameters:type_name -> ai_service.CreateAgentTaskRequest.ParametersEntry
	19, // 2: ai_service.GetTaskStatusResponse.result:type_name -> ai_service.GetTaskStatusResponse.ResultEntry
	9,  // 3: ai_service.ListUserTasksResponse.tasks:type_name -> ai_service.UserTask
	12, // 4: ai_service.InferModelRequest.messages:type_name -> ai_service.ChatMessage
	20, // 5: ai_service.InferModelRequest.parameters:type_name -> ai_service.InferModelRequest.ParametersEntry
	21, // 6: ai_service.ExecuteWorkflowRequest.inputs:type_name -> ai_service.ExecuteWorkflowRequest.InputsEntry
	22, // 7: ai_service.ExecuteWorkflowRequest.config:type_name -> ai_service.ExecuteWorkflowRequest.ConfigEntry
	23, // 8: ai_service.ExecuteWorkflowResponse.outputs:type_name -> ai_service.ExecuteWorkflowResponse.OutputsEntry
	16, // 9: ai_service.ExecuteWorkflowResponse.steps:type_name -> ai_service.WorkflowStep
	24, // 10: ai_service.WorkflowStep.outputs:type_name -> ai_service.WorkflowStep.OutputsEntry
	0,  // 11: ai_service.AIService.CreateAgentTask:input_type -> ai_service.CreateAgentTaskRequest
	2,  // 12: ai_service.AIService.GetTaskStatus:input_type -> ai_service.GetTaskStatusRequest
	4,  // 13: ai_service.AIService.CancelTask:input_type -> ai_service.CancelTaskRequest
	6,  // 14: ai_service.AIService.GetAgentStats:input_type -> ai_service.GetAgentStatsRequest
	8,  // 15: ai_service.AIService.ListUserTasks:input_type -> ai_service.ListUserTasksRequest
	11, // 16: ai_service.AIService.InferModel:input_type -> ai_service.InferModelRequest
	14, // 17: ai_service.AIService.ExecuteWorkflow:input_type -> ai_service.ExecuteWorkflowRequest
	1,  // 18: ai_service.AIService.CreateAgentTask:output_type -> ai_service.CreateAgentTaskResponse
	3,  // 19: ai_service.AIService.GetTaskStatus:output_type -> ai_service.GetTaskStatusResponse
	5,  // 20: ai_service.AIService.CancelTask:output_type -> ai_service.CancelTaskResponse
	7,  // 21: ai_service.AIService.GetAgentStats:output_type -> ai_service.GetAgentStatsResponse
	10, // 22: ai_service.AIService.ListUserTasks:output_type -> ai_service.ListUserTasksResponse
	13, // 23: ai_service.AIService.InferModel:output_type -> ai_service.InferModelResponse
	15, // 24: ai_service.AIService.ExecuteWorkflow:output_type -> ai_service.ExecuteWorkflowResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
