// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ai_service_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 流式聊天请求
type StreamChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                                            // 模型名称
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                     // 用户ID
	Messages      []*StreamChatMessage   `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`                                                                               // 消息历史
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatRequest) Reset() {
	*x = StreamChatRequest{}
	mi := &file_ai_service_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatRequest) ProtoMessage() {}

func (x *StreamChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatRequest.ProtoReflect.Descriptor instead.
func (*StreamChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamChatRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StreamChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamChatRequest) GetMessages() []*StreamChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *StreamChatRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// 流式聊天响应
type StreamChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                      // 内容片段
	IsComplete     bool                   `protobuf:"varint,2,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`             // 是否完成
	ModelUsed      string                 `protobuf:"bytes,3,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`                 // 使用的模型
	TokensUsed     int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`             // 使用的token数
	PointsConsumed int32                  `protobuf:"varint,5,opt,name=points_consumed,json=pointsConsumed,proto3" json:"points_consumed,omitempty"` // 消耗的积分
	FinishReason   string                 `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`        // 完成原因
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                          // 错误信息（如果有）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamChatResponse) Reset() {
	*x = StreamChatResponse{}
	mi := &file_ai_service_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatResponse) ProtoMessage() {}

func (x *StreamChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatResponse.ProtoReflect.Descriptor instead.
func (*StreamChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamChatResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *StreamChatResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *StreamChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *StreamChatResponse) GetPointsConsumed() int32 {
	if x != nil {
		return x.PointsConsumed
	}
	return 0
}

func (x *StreamChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *StreamChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 流式工作流执行请求
type StreamWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`                                           // 工作流名称
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                             // 用户ID
	Inputs        map[string]string      `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 输入参数
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWorkflowRequest) Reset() {
	*x = StreamWorkflowRequest{}
	mi := &file_ai_service_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkflowRequest) ProtoMessage() {}

func (x *StreamWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StreamWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *StreamWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamWorkflowRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *StreamWorkflowRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 流式工作流执行响应
type StreamWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`                                                                                 // 工作流执行ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                                                           // 当前状态
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`                                                                              // 当前执行步骤
	StepOutput    string                 `protobuf:"bytes,4,opt,name=step_output,json=stepOutput,proto3" json:"step_output,omitempty"`                                                                                 // 步骤输出
	Progress      float32                `protobuf:"fixed32,5,opt,name=progress,proto3" json:"progress,omitempty"`                                                                                                     // 进度百分比
	IsComplete    bool                   `protobuf:"varint,6,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`                                                                                // 是否完成
	FinalOutputs  map[string]string      `protobuf:"bytes,7,rep,name=final_outputs,json=finalOutputs,proto3" json:"final_outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 最终输出
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                                                                                                             // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWorkflowResponse) Reset() {
	*x = StreamWorkflowResponse{}
	mi := &file_ai_service_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkflowResponse) ProtoMessage() {}

func (x *StreamWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StreamWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_stream_proto_rawDescGZIP(), []int{3}
}

func (x *StreamWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StreamWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamWorkflowResponse) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *StreamWorkflowResponse) GetStepOutput() string {
	if x != nil {
		return x.StepOutput
	}
	return ""
}

func (x *StreamWorkflowResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StreamWorkflowResponse) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *StreamWorkflowResponse) GetFinalOutputs() map[string]string {
	if x != nil {
		return x.FinalOutputs
	}
	return nil
}

func (x *StreamWorkflowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 流式聊天消息
type StreamChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // 角色：user/assistant/system
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChatMessage) Reset() {
	*x = StreamChatMessage{}
	mi := &file_ai_service_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChatMessage) ProtoMessage() {}

func (x *StreamChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChatMessage.ProtoReflect.Descriptor instead.
func (*StreamChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_service_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StreamChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StreamChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_ai_service_stream_proto protoreflect.FileDescriptor

const file_ai_service_stream_proto_rawDesc = "" +
	"\n" +
	"\x17ai_service_stream.proto\x12\n" +
	"ai_service\"\x94\x02\n" +
	"\x11StreamChatRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\bmessages\x18\x03 \x03(\v2\x1d.ai_service.StreamChatMessageR\bmessages\x12M\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2-.ai_service.StreamChatRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x12StreamChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vis_complete\x18\x02 \x01(\bR\n" +
	"isComplete\x12\x1d\n" +
	"\n" +
	"model_used\x18\x03 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12'\n" +
	"\x0fpoints_consumed\x18\x05 \x01(\x05R\x0epointsConsumed\x12#\n" +
	"\rfinish_reason\x18\x06 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\xd9\x02\n" +
	"\x15StreamWorkflowRequest\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12E\n" +
	"\x06inputs\x18\x03 \x03(\v2-.ai_service.StreamWorkflowRequest.InputsEntryR\x06inputs\x12E\n" +
	"\x06config\x18\x04 \x03(\v2-.ai_service.StreamWorkflowRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x03\n" +
	"\x16StreamWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\x12\x1f\n" +
	"\vstep_output\x18\x04 \x01(\tR\n" +
	"stepOutput\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x02R\bprogress\x12\x1f\n" +
	"\vis_complete\x18\x06 \x01(\bR\n" +
	"isComplete\x12Y\n" +
	"\rfinal_outputs\x18\a \x03(\v24.ai_service.StreamWorkflowResponse.FinalOutputsEntryR\ffinalOutputs\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x1a?\n" +
	"\x11FinalOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x11StreamChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\xa5\x02\n" +
	"\x0fAIStreamService\x12M\n" +
	"\n" +
	"StreamChat\x12\x1d.ai_service.StreamChatRequest\x1a\x1e.ai_service.StreamChatResponse0\x01\x12`\n" +
	"\x15StreamWorkflowExecute\x12!.ai_service.StreamWorkflowRequest\x1a\".ai_service.StreamWorkflowResponse0\x01\x12a\n" +
	"\x16StreamWorkflowGenerate\x12!.ai_service.StreamWorkflowRequest\x1a\".ai_service.StreamWorkflowResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_ai_service_stream_proto_rawDescOnce sync.Once
	file_ai_service_stream_proto_rawDescData []byte
)

func file_ai_service_stream_proto_rawDescGZIP() []byte {
	file_ai_service_stream_proto_rawDescOnce.Do(func() {
		file_ai_service_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_stream_proto_rawDesc), len(file_ai_service_stream_proto_rawDesc)))
	})
	return file_ai_service_stream_proto_rawDescData
}

var file_ai_service_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_service_stream_proto_goTypes = []any{
	(*StreamChatRequest)(nil),      // 0: ai_service.StreamChatRequest
	(*StreamChatResponse)(nil),     // 1: ai_service.StreamChatResponse
	(*StreamWorkflowRequest)(nil),  // 2: ai_service.StreamWorkflowRequest
	(*StreamWorkflowResponse)(nil), // 3: ai_service.StreamWorkflowResponse
	(*StreamChatMessage)(nil),      // 4: ai_service.StreamChatMessage
	nil,                            // 5: ai_service.StreamChatRequest.ParametersEntry
	nil,                            // 6: ai_service.StreamWorkflowRequest.InputsEntry
	nil,                            // 7: ai_service.StreamWorkflowRequest.ConfigEntry
	nil,                            // 8: ai_service.StreamWorkflowResponse.FinalOutputsEntry
}
var file_ai_service_stream_proto_depIdxs = []int32{
	4, // 0: ai_service.StreamChatRequest.messages:type_name -> ai_service.StreamChatMessage
	5, // 1: ai_service.StreamChatRequest.parameters:type_name -> ai_service.StreamChatRequest.ParametersEntry
	6, // 2: ai_service.StreamWorkflowRequest.inputs:type_name -> ai_service.StreamWorkflowRequest.InputsEntry
	7, // 3: ai_service.StreamWorkflowRequest.config:type_name -> ai_service.StreamWorkflowRequest.ConfigEntry
	8, // 4: ai_service.StreamWorkflowResponse.final_outputs:type_name -> ai_service.StreamWorkflowResponse.FinalOutputsEntry
	0, // 5: ai_service.AIStreamService.StreamChat:input_type -> ai_service.StreamChatRequest
	2, // 6: ai_service.AIStreamService.StreamWorkflowExecute:input_type -> ai_service.StreamWorkflowRequest
	2, // 7: ai_service.AIStreamService.StreamWorkflowGenerate:input_type -> ai_service.StreamWorkflowRequest
	1, // 8: ai_service.AIStreamService.StreamChat:output_type -> ai_service.StreamChatResponse
	3, // 9: ai_service.AIStreamService.StreamWorkflowExecute:output_type -> ai_service.StreamWorkflowResponse
	3, // 10: ai_service.AIStreamService.StreamWorkflowGenerate:output_type -> ai_service.StreamWorkflowResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ai_service_stream_proto_init() }
func file_ai_service_stream_proto_init() {
	if File_ai_service_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_stream_proto_rawDesc), len(file_ai_service_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_stream_proto_goTypes,
		DependencyIndexes: file_ai_service_stream_proto_depIdxs,
		MessageInfos:      file_ai_service_stream_proto_msgTypes,
	}.Build()
	File_ai_service_stream_proto = out.File
	file_ai_service_stream_proto_goTypes = nil
	file_ai_service_stream_proto_depIdxs = nil
}
